-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 10:59:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ges
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ges
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ges` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema gestionsena
-- -----------------------------------------------------
USE `ges` ;

-- -----------------------------------------------------
-- Table `ges`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ges`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ges`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ges`.`Role` (
  `idRole` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ges`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ges`.`Usuario` (
  `idUsuario` INT GENERATED ALWAYS AS () VIRTUAL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Role_idRole` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Role_idx` (`Role_idRole` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Role`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `ges`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ges`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ges`.`Material` (
  `idPaquete` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idPaquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ges`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ges`.`Entrega` (
  `Paquete_idPaquete` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Paquete_idPaquete`, `Usuario_idUsuario`),
  INDEX `fk_Paquete_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Paquete_has_Usuario_Paquete1_idx` (`Paquete_idPaquete` ASC) VISIBLE,
  CONSTRAINT `fk_Paquete_has_Usuario_Paquete1`
    FOREIGN KEY (`Paquete_idPaquete`)
    REFERENCES `ges`.`Material` (`idPaquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paquete_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `ges`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
